Repository meshery/meshkit, pull requests merged in 2022-09, with the labels that each got.

#206 [Feat] Component Generation Factory
  helpers/component_info.json
  models/interfaces.go
  models/meshmodel/core/v1alpha1/component.go
  utils/artifacthub/error.go
  utils/artifacthub/package.go
  utils/artifacthub/package_test.go
  utils/artifacthub/ranker.go
  utils/artifacthub/ranker_test.go
  utils/artifacthub/scanner.go
  utils/artifacthub/scanner_test.go
  utils/component/error.go
  utils/component/generator.go
  utils/component/generator_test.go
  utils/component/utils.go
  utils/cue.go
  utils/error.go
  utils/manifests/getComponents.go
Labels: area/patterns

#212 fix(ci/lint): fix failing lint checks
  cmd/errorutil/internal/coder/commands.go
  cmd/errorutil/internal/coder/file.go
  cmd/errorutil/internal/component/component.go
  cmd/errorutil/internal/error/export.go
  cmd/errorutil/internal/error/summary.go
  database/error.go
  errors/errors.go
  logger/logger.go
  utils/events/event.go
  utils/git.go
  utils/kubernetes/apply-helm-chart.go
  utils/kubernetes/helm.go
  utils/kubernetes/kompose/convert.go
  utils/manifests/utils.go
  utils/sortversions.go
  utils/utils.go
  utils/walker/git.go
Labels: area/ci, kind/chore

#213 [bug] Update dictionary
  utils/artifacthub/package_test.go
  utils/manifests/utils.go
Labels: kind/bug, kind/chore

#214 Add Undeploy method for controllers
  go.mod
  go.sum
  models/controllers/controllers.go
  models/controllers/helpers.go
  models/controllers/meshery_broker.go
  models/controllers/meshery_operator.go
  models/controllers/meshsync.go
  utils/artifacthub/package_test.go
Labels: area/lifecycle
