Repository meshery/meshkit, pull requests merged in 2022-04, with the labels that each got.

#164 [Feat] Add utility functions for leveraging the capabilities offered by kompose
  Makefile
  build/Makefile.core.mk
  build/Makefile.show-help.mk
  errors/errors.go
  go.mod
  go.sum
  helpers/component_info.json
  utils/kubernetes/kompose/convert.go
  utils/kubernetes/kompose/error.go
Labels: component/extension

#171 Fix vet errors
  .golangci.yml
  cmd/errorutil/internal/coder/node.go
  go.mod
  go.sum
  logger/controller.go
  logger/logger.go
  models/oam/core/v1alpha1/doc.go
  utils/error.go
  utils/git.go
  utils/kubernetes/apply-helm-chart.go
  utils/kubernetes/client.go
  utils/kubernetes/error.go
  utils/kubernetes/expose/traverser.go
  utils/kubernetes/kubernetes.go
  utils/kubernetes/service_test.go
  utils/manifests/generateComponent.go
  utils/sortversions.go
  utils/utils.go
  utils/walker/git.go
Labels: kind/chore, language/go

#174 fixed Helm issue where namespace was not persisted
  utils/kubernetes/apply-helm-chart.go
Labels: language/go

#175 fixed logger types
  logger/controller.go
  logger/logger.go
Labels: kind/chore, language/go
