Repository meshery/meshkit, pull requests merged in 2023-10, with the labels that each got.

#382 [environment] Update Environment Schema
  schemas/configuration/environment.json
Labels: kind/chore

#384 Add new workspace schema
  schemas/configuration/uiSchemaWorkspace.json
  schemas/configuration/workspace.json
  schemas/schemaProvider.go
Labels: kind/chore

#388 [chore] add .DS_Store
  .gitignore
Labels: kind/chore

#383 feat:retrieve registrants and number of models components relationshi…
  models/meshmodel/core/v1alpha1/host.go
  models/meshmodel/registry/registry.go
Labels: area/meshmodel

#389 Update ci configuration and fixed the code error and security issue
  .github/workflows/ci.yml
  .golangci.yml
  cmd/errorutil/internal/coder/commands.go
  cmd/syncmodutil/internal/modsync/sync.go
  go.mod
  go.sum
  models/controllers/meshsync.go
  utils/cue.go
  utils/kubernetes/apply-manifest.go
  utils/kubernetes/client.go
  utils/kubernetes/expose/expose.go
  utils/kubernetes/helm.go
  utils/kubernetes/kompose/composefile.go
  utils/kubernetes/kompose/convert.go
  utils/manifests/generateComponent.go
  utils/manifests/utils.go
  utils/walker/git.go
Labels: dependencies, security, docker

#393 [CI] fix golangci
  go.mod
  go.sum
Labels: area/ci

#404 [chore] Fix go.mod
  go.mod
  go.sum
  utils/kubernetes/kompose/convert.go
Labels: area/ci
