Repository meshery/meshkit, pull requests merged in 2023-01, with the labels that each got.

#247 [Refactor] Add `ErrorV2` struct
  errors/errors.go
  errors/types.go
Labels: area/lifecycle

#255 [chore] Drop Relationships Table on Meshery Server Shut Down
  models/meshmodel/registry.go
Labels: kind/bug, kind/chore

#256 [bug] Fix MeshModel
  models/meshmodel/registry.go
Labels: kind/bug

#253 Upgrade Kompose 1.28
  .github/workflows/ci.yml
  go.mod
  go.sum
Labels: kind/chore, language/go

#260 Fix go mod sync utility
  cmd/syncmodutil/internal/modsync/sync.go
Labels: language/go
